# Welcome to Evan's Unofficial offical website!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Merch
email: inallseriousness247@gmail.com
description: > # this means to ignore newlines until "baseurl:" Evant is SME start-up based in Singapore. We specialise in studying A-math as well as other difficult topics and not pass it in.The vision of our enterprise is to expand overseas and broaden our customer base to be able to do nothing at all
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: i_am_evan01
github_username:  evant01

# Build settings
markdown: kramdown
